### ISSUE TITLE
[FEATURE]: 希望支持 containerd 标准输出

### ISSUE THREAD

**Issue by PungYoung** [alibaba/ilogtail#1038]
目前好像只支持docker的标准输出，希望支持containerd

**Comment by yyuuttaaoo** [comment]
是否和这个问题重复？ #1037
ilogtail是支持containerd stdout采集的

**Comment by yyuuttaaoo** [comment]
@PungYoung 补丁已经合入主干了，应该已经修复了问题。
如果方便的话，请帮忙登记一下您的使用场景 https://github.com/alibaba/ilogtail/issues/693
如果有使用案例也欢迎提交到 https://github.com/alibaba/ilogtail/tree/main/example_config/user_contrib
