### ISSUE TITLE
[BUG]:flusher_sls发往sls报 PostBodyInvalid error msg:fail to parse protobuf

### ISSUE THREAD

**Issue by joerong666** [alibaba/ilogtail#1085]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version: tag v1.7.0
  
- Yaml configuration:
enable: true
inputs:
  - Type: file_log          
    LogPath: ./data/simple         
    FilePattern: simple*.log
    MaxDepth: 3
    CompressType: none
flushers:
  - Type: flusher_stdout   
    OnlyStdout: true
  - Type: flusher_sls
    Region: cn-hangzhou
    Endpoint: cn-hangzhou.log.aliyuncs.com
    ProjectName: xxx
    LogstoreName: xxx
    

- ilogtail.LOG:
[warning]       [026705]        /workspace/ilogtail/core/sender/Sender.cpp:388          SendFail:other error    Operation:discard data  Suggestion:no suggestion RequestId:64E5A3396411E59BD004F96B      StatusCode:400  ErrorCode:PostBodyInvalid       ErrorMessage:fail to parse protobuf     ResponseTime:0  Region:cn-hangzhou      Project:xxx Logstore:xxx Config:config#/workspace/ilogtail/debug/./user_yaml_config.d/file_simple.yaml

- logtail_plugin.LOG:

**Comment by joerong666** [comment]
CompressType: none
压缩类型默认是lz4，最开始我没有设置，就用默认的lz4，但不行，看之前网也有人提过类似问题，我改成none压缩类型还是不行
https://github.com/AliyunContainerService/log-pilot/issues/206

**Comment by yyuuttaaoo** [comment]
这个问题的原因是ilogtail的1.7.0版本存在一个bug，当使用插件向SLS发送数据时会因为携带time_ns字段导致服务端接收失败，这个bug在 #1012 中已经修复，升级到1.7.1就可以解决。
