### ISSUE TITLE
[BUG]: version 1.7.1 processor_json cannot maintain backward compatibility when parsing json arrays.

### ISSUE THREAD

**Issue by tatianguiqu** [alibaba/ilogtail#1088]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version: 1.7.1
  
- Yaml configuration: processor_json

- detail:
Previously, when the json value was an array, it would not be broken apart but directly parsed into the current field, such as a:[1]. However, the new version directly parses the value when it's an array. So, the previous example would become a[0]:1. If the array is empty, it used to be a:[], and now the field is lost because it's directly omitted. Before, only when the value was a dictionary would it recursively parse the fields and use an underscore to join fields. Now, arrays are also parsed, and the index is appended to the field, like [index].

**Comment by liangry** [comment]
Array expansion is a new feature of the plugin, I think a switch option should be added to allow users to choose whether to expand arrays in JSON to maintain backward compatibility.
