### ISSUE TITLE
[异常处理]指针使用没有判空处理

### ISSUE THREAD

**Issue by jianxiyueyingchen** [alibaba/ilogtail#1125]
>     char* header = new char[INT32_FLAG(file_encryption_header_length) + 1];
>     int32_t nbytes = (int32_t)fread(header, 1, INT32_FLAG(file_encryption_header_length), pFile);
代码里面多处指针没有判空处理

**Comment by yyuuttaaoo** [comment]
如果内存都申请不出来，我觉得程序崩溃也没太大问题。另外，这里的代码没有加no throw，如果申请失败应该会抛异常
