### ISSUE TITLE
[QUESTION]: ilogtail 收集日志时候异常退出

### ISSUE THREAD

**Issue by hehua2018** [alibaba/ilogtail#1217]
Before asking a question, please first consider:

- Searching [existing discussions](https://github.com/alibaba/ilogtail/discussions/)
- Searching [existing issues](https://github.com/alibaba/ilogtail/issues/)
- Searching [English Doc](https://github.com/alibaba/ilogtail/tree/main/docs/en)
- Searching Google

-------
ilogtail 部署方式容器边车模式，收集应用日志
版本：1.4.0
![image](https://github.com/alibaba/ilogtail/assets/36179722/f6c41efd-4f34-4309-85c2-9e774a004a1d)
![image](https://github.com/alibaba/ilogtail/assets/36179722/bd293771-5940-4189-8eb3-bcf4194bffcf)

日志文件如下：
[ilogtail.LOG](https://github.com/alibaba/ilogtail/files/13246303/ilogtail.LOG)

[logtail_plugin.LOG](https://github.com/alibaba/ilogtail/files/13246304/logtail_plugin.LOG)

提问之前，建议先在 iLogtail 社区寻找答案。

- 查看 [存在的 discussions](https://github.com/alibaba/ilogtail/discussions/)
- 查看 [存在的 issues](https://github.com/alibaba/ilogtail/issues/)
- 查看 [中文文档](https://ilogtail.gitbook.io/ilogtail-docs/about/readme)
- 查看 Google

如果仍然无法找到答案，我们建议您在[discussions](https://github.com/alibaba/ilogtail/discussions/)进行提问。

**Comment by linrunqi08** [comment]
可以发下ilogtail.LOG和logtail_plugin.LOG

**Comment by hehua2018** [comment]
[ilogtail.LOG](https://github.com/alibaba/ilogtail/files/13246232/ilogtail.LOG)
[logtail_plugin.LOG](https://github.com/alibaba/ilogtail/files/13246234/logtail_plugin.LOG)
这个是我的日志，我升级到1.8.0版本也是这样

**Comment by linrunqi08** [comment]
是的，关键报错是这个：
[2023-11-02 18:18:12.855159]	[error]	[19]	/src/core/monitor/Monitor.cpp:178		Resource used by program exceeds upper limit:prepare restart Logtail	cpu_usage:0.01595	mem_rss:155

**Comment by hehua2018** [comment]
请问这个是要扩大内存吗？

**Comment by hehua2018** [comment]
重启了不是应该会自动起来的，怎么没有启动成功

**Comment by yyuuttaaoo** [comment]
> 重启了不是应该会自动起来的，怎么没有启动成功

开源版依赖k8s的健康检查进行重启
