### ISSUE TITLE
[BUG]:  field is missing

### ISSUE THREAD

**Issue by beyond688** [alibaba/ilogtail#124]
配置文件中使用了processor_split_log_regex插件后，发现日志中丢失了文件路径__tag__:__path__字段

**Comment by messixukejia** [comment]
因为logtail 插件跟C++部分实现的差异，所以使用了插件处理数据后，会__tag__:__path__将不在是tag字读。
详见https://help.aliyun.com/document_detail/64957.html

索引配置方法：https://help.aliyun.com/document_detail/90732.html
