### ISSUE TITLE
采集的时候怎么过滤掉指定Namespace的收集呢？

### ISSUE THREAD

**Issue by mark8s** [alibaba/ilogtail#1243]
```yaml
ExcludeEnv:
          POD_NAMESPACE: "^(kube-system|kube-public|kube-node-lease)$"
```

使用这种方式，没那么精确。有没有更好的方式啊？大哥们

**Comment by yyuuttaaoo** [comment]
https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/input/file-log.md
用这个怎么样？ K8sNamespaceRegex

**Comment by mark8s** [comment]
@yyuuttaaoo 不太匹配。但没其他的办法暂时。
