### ISSUE TITLE
[QUESTION]: 采集日志文件名正则匹配

### ISSUE THREAD

**Issue by Arunchen** [alibaba/ilogtail#1260]
这边采集canal的实例日志，但是每个实例目录下有两个文件名字，一个实例名字的.log，一个meta.log,  想要通配*.log并排除meta.log的采集，但没查到相应配置

**Comment by 7y-9** [comment]
ilogtail 使用的是标准的glob匹配，可以写glob表达式的。

或者将meta.log添加至监听黑名单。

**Comment by Arunchen** [comment]
@7y-9 非常感谢
