### ISSUE TITLE
win10编译ilogtail失败，Build iLogtail source failed.

### ISSUE THREAD

**Issue by pigwantacat** [alibaba/ilogtail#1269]
## 问题

win10编译ilogtail失败

## 编译环境

操作系统：Windows10 

IDE：GoLand2022.3.4、VS2022

gcc、g++：

```txt
C:\Users\zhb>gcc --version
gcc (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\Users\zhb>g++ --version
g++ (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## 修改配置

![image](https://github.com/alibaba/ilogtail/assets/79680042/25b48295-0295-469d-87c2-891af390ee66)

## 日志打印

![image](https://github.com/alibaba/ilogtail/assets/79680042/ee62518b-396e-4059-aac7-ec233dbb682f)

## 控制台打印

![image](https://github.com/alibaba/ilogtail/assets/79680042/28a2328c-e876-41b9-be20-a8aa642e51ba)

**Comment by quzard** [comment]
看报错应该是依赖库没找到

**Comment by pigwantacat** [comment]
> 看报错应该是依赖库没找到

是的
