### ISSUE TITLE
[QUESTION]: 请问如何单独创建索引？

### ISSUE THREAD

**Issue by beyond688** [alibaba/ilogtail#127]
__tag__:__path__等字段不再具备原生字段索引，需单独创建索引。
请问如何单独创建索引？

![image](https://user-images.githubusercontent.com/39320802/163758502-9187ae80-f413-4e5c-bc5e-9076121f5141.png)

**Comment by messixukejia** [comment]
https://help.aliyun.com/document_detail/90732.html

按照上述文档，增加下__tag__:__path__索引即可

**Comment by beyond688** [comment]
你好，我用的是自己安装并配置的iLogtail在服务器上采集日志往kafka发送的，没有使用日志服务SLS，请问这样的情况怎么处理呢？
