### ISSUE TITLE
[BUG]: 运维脚本cp /dev/nul */log 可能会造成从文件头重复采集的问题

### ISSUE THREAD

**Issue by 7y-9** [alibaba/ilogtail#1274]
**Describe the bug**
运维清理脚本 cp /dev/nul */log 会造成文件从头重复采集

**iLogtail Running Environment**
Linux 5.10.109-1.el7.x86_64 

- ilogtail version:
  1.8.1-release

关键日志：
File signature is same but size decrease, read from now fileSize

**Comment by yyuuttaaoo** [comment]
能否具体一些，比如cp /dev/null xxx.log。xxx.log是否还有别的进程在写数据等信息

**Comment by 7y-9** [comment]
> 能否具体一些，比如cp /dev/null xxx.log。xxx.log是否还有别的进程在写数据等信息

是的。这个文件的fd同时被写入程序和ilogtail所持有，然后运维的脚本cp /dev/null xxx.log 就会有一定概率重复采集。

**Comment by yyuuttaaoo** [comment]
重复内容是老文件内容开头部分还是什么位置的？

**Comment by 7y-9** [comment]
> 重复内容是老文件内容开头部分还是什么位置的？
> 
> 如果有另一个进程在读取 xxx.log 当 cp /dev/null xxx.log 命令执行时，那么这个正在读取的进程的行为将取决于它读取时的具体时机和方式。
> 
> 文件大小变化：一旦 cp /dev/null xxx.log 命令执行，xxx.log 文件的大小会瞬间变成0。此时，任何尝试读取新内容的进程都会立即遇到文件结束（EOF），因为文件已经是空的了。
> 
> 已打开的文件描述符：如果读取进程已经打开了文件并且开始读取，它可能会继续读取到它开始读取时文件中的内容，直到它到达文件末尾。这是因为在 Unix 类系统中，打开的文件是通过文件描述符（file descriptor）来管理的。当一个进程打开文件时，它获得文件的一个描述符，即使文件内容在磁盘上改变，通过该描述符的读取操作还是基于文件被打开时的状态。
> 
> 缓存和缓冲区：操作系统和进程可能会将文件内容缓存到内存中。如果读取进程在 cp 命令执行前已经将数据读入到缓存或缓冲区，那么它可能仍然能够读取到 cp 命令执行前的原始数据，即使文件在磁盘上已经被清空。
> 
> 因此，如果读进程在文件内容被清空之前就开始了读取操作，它可能会读到一部分或全部原有内容，取决于读取操作和 cp 命令执行的相对时机。如果读进程在文件被清空后开始读取，它将看到一个空文件。
> 
> 在实际生产环境中，如果需要清空日志文件同时保证不影响正在读取这些文件的进程，通常需要额外的协调机制，比如日志轮替（log rotation），这样可以在保留旧日志的同时创建新的日志文件供写入。

感谢回复,已经能很好的解答我的疑问。
我将关闭这个issue
