### ISSUE TITLE
[QUESTION]:tag:__path__等字段不再具备原生字段索引，需单独创建索引。

### ISSUE THREAD

**Issue by beyond688** [alibaba/ilogtail#130]
感谢之前的回复：https://github.com/alibaba/ilogtail/issues/127

不过我是自己安装并配置的iLogtail在服务器上采集日志往kafka发送的，没有使用日志服务SLS，请问这样的情况怎么处理呢？
当我使用了processor_split_log_regex插件后，kafka中收到的数据没有了__tag__:__path__字段。

**Comment by messixukejia** [comment]
完整的采集配置发下

**Comment by beyond688** [comment]
`{
   "metrics":
    {
        "##1.0##kafka_output_test3":
        {
           "category": "file",
           "log_type": "apsara_log",
           "separator": "",
           "keys": [""],
           "regex": [""],
           "log_begin_regex": [""],
           "log_begin_regexs": [""],
           "logBeginRegex": [""],
           "logBeginRegexs": [""],
           "log_path": "/home/admin/liujh/sysm-data/sysm-data-invilid-2.0.0/logs/",
           "file_pattern": "*.log",
           "create_time": 1631018645,
           "defaultEndpoint": "",
           "delay_alarm_bytes": 0,
           "delay_skip_bytes": 0,
           "discard_none_utf8": false,
           "discard_unmatch": false,
           "docker_exclude_env":
            {},
           "docker_exclude_label":
            {},
           "docker_file": false,
           "docker_include_env":
            {},
           "docker_include_label":
            {},
           "enable": true,
           "enable_tag": false,
           "file_encoding": "utf8",
           "filter_keys": [
            ],
           "filter_regs":[
            ],
           "group_topic": "",
           "plugin":
            {
               "processors":
                [
                   {
                        "detail": {
                            "SplitRegex": "\\s*[0-9]{4}-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9].*",
                            "SplitKey": "content"
                        },
                        "type": "processor_split_log_regex"
                   },
                   {
                     "type":"processor_add_fields",
                     "detail":
                     {
                         "Fields": {
                            "serviceLine": "csp",
                            "appName": "csp-hermes",
                            "hostName": "tc-dev-mid-monitor03"
                         }
                     }
                   }
               ],
               "flushers":
                [
                    {
                        "type": "flusher_kafka",
                        "detail":
                         {
                            "Brokers":
                             [
                                "10.7.0.37:9092"
                             ],
                            "Topic": "logtail-flusher-kafka2"
                         }
                     }
                ]
            },
           "local_storage": true,
           "log_tz": "",
           "max_depth": 10,
           "max_send_rate": -1,
           "merge_type": "topic",
           "preserve": true,
           "preserve_depth": 1,
           "priority": 0,
           "raw_log": false,
           "aliuid": "",
           "region": "",
           "project_name": "",
           "send_rate_expire": 0,
           "sensitive_keys":
            [],
           "shard_hash_key":
            [],
           "tail_existed": false,
           "time_key": "",
           "timeformat": "",
           "topic_format": "none",
           "tz_adjust": false,
           "version": 1,
           "advanced":
            {
               "force_multiconfig": false,
               "tail_size_kb": 1024
            }
        }
    }
}`

**Comment by messixukejia** [comment]
processor_split_log_regex增加下PreserveOthers: true配置项。相见processor_split_log_regex代码

**Comment by beyond688** [comment]
感谢
