### ISSUE TITLE
[QUESTION]: 插件系统为何一路LogStoreConfig创建一套协程？

### ISSUE THREAD

**Issue by JeffPhoneix** [alibaba/ilogtail#131]
从官方分享的LogTail文档中看，LogTail的初衷是要解决Filebeat为每路采集文件都创建一套协程这种暴力做法，但从插件系统上看，目前每路LogStoreConfig基本都是一套协程（类似一个完整Pipeline的做法)。

这里想请教下，是否在golang的插件系统中性能已经不再重要了？能详细说明下C++部分和插件系统的关系吗？

**Comment by messixukejia** [comment]
logtail文件采集的逻辑都在C++部分（暂未开源），Linux下文件采集才有了event通知机制，不是暴力轮询的方法。插件部分，更多的逻辑文件采集后的Porcess处理，所以是按照采集到的文本内容串行处理的场景。

插件跟C++部分的关系，可以参见https://developer.aliyun.com/article/727322
