### ISSUE TITLE
[QUESTION]: 写kafka的flusher没有找到重试的地方？

### ISSUE THREAD

**Issue by JeffPhoneix** [alibaba/ilogtail#132]
通读iLogTail中写kafka的没有重试的地方。即使是写SLS也没有重试。想请教下这里对失败重试的设计是如何的？
flusher_kafka.go中对于失败只是简单的打印一条错误日志。是只要写不进，就不管了吗？此时日志就丢了？

**Comment by messixukejia** [comment]
kafka使用了producer   sarama.AsyncProducer库，异步发送，里面会有重试。

SLS写入有严格的可靠性保证，这点可以放心，也是异步发送的机制。logtail.SendPbV2并不是直接就发送日志，而是放到内部队列中，失败会有重试机制。这部分目前暂未开源，后续会开源出来。
