### ISSUE TITLE
[QUESTION]:  iLogtail正常运行和采集，但是ilogtail.LOG日志中有报错信息

### ISSUE THREAD

**Issue by beyond688** [alibaba/ilogtail#136]
错误日志如下：
[2022-04-25 15:51:56.031582]    [error] [001268]        /build/logtail/controller/EventDispatcher.cpp:1651              Bind domain socket:Failed       98:Address already in use      File Descriptor:23

请问这个端口是否可以配置解决报错问题？

**Comment by messixukejia** [comment]
是不是一台机器上启动了两个logtail？

**Comment by beyond688** [comment]
> 是不是一台机器上启动了两个logtail？

是的，在阿里云服务器上装的，阿里云服务器上本身有一个自带的logtail，之后又安装了一个，因为同时安装的机器比较多，所以不太好关闭阿里云服务器自带的。

1、请问这个端口是否可以配置成其他的？
2、请问这个报错有什么影响？

**Comment by messixukejia** [comment]
一台机器上装一个logtal就够了，没必要安装两个。
配置项暂时没有对外暴露。这个会影响文件事件的监听。

6月份我们完整开源logtail退出社区版后，如果想用社区版就不会有这个问题了。

**Comment by beyond688** [comment]
> 一台机器上装一个logtal就够了，没必要安装两个。 配置项暂时没有对外暴露。这个会影响文件事件的监听。
> 
> 6月份我们完整开源logtail退出社区版后，如果想用社区版就不会有这个问题了。

好的，感谢，请问把阿里云服务器上自带的logtail关闭对使用阿里云服务器会有影响吗

**Comment by messixukejia** [comment]
请问，你这是生产环境吗？是否在配合着SLS服务在使用？如果没有使用可以关掉。
