### ISSUE TITLE
如何使用ilogtail开源版本配置采集promethues的数据呢？

### ISSUE THREAD

**Issue by yanyanguo** [alibaba/ilogtail#1380]
我看到商业版是有配置的：https://developer.aliyun.com/article/871634#slide-1
但是商业版上是json的配置

我参照链接的配置 我的配置是写的这样的：
enable: true
inputs:
  -Type: service_prometheus
    Yaml: "global:  
             scrape_interval: 15s
             evaluation_interval: 15s
             scrape_configs:  
             - job_name: 'prometheus'
               static_configs:  
               - targets: ['ip:port']"
flushers:
  -Type: flusher_stdout
    OnlyStdout: true

    
    
  plugin日志里报错:
  2024-02-29 07:03:12 [ERR] [plugin_export.go:124] [LoadConfig] AlarmType:CONFIG_LOAD_ALARM       load config error, project:     logstore:       config:test/1   error:illegal prometheus configuration file __test/1: cannot unmarshal data: yaml: mapping values are not allowed in this context
  
这个采集的话应该怎么配置？ 在/usr/local/ilogtail/config/local 下的配置文件 yaml或者json的都可以吗？

**Comment by yanyanguo** [comment]
不懂如何参照商业版的去进行配置

**Comment by messixukejia** [comment]
![image](https://github.com/alibaba/ilogtail/assets/13250519/e1626a6a-55b5-469a-9438-665a1aaa0daf)

参考转换成yaml结构就可以了
![image](https://github.com/alibaba/ilogtail/assets/13250519/8299de82-a74e-4a3e-a7c0-fce62e75c090)

**Comment by messixukejia** [comment]
整体思路是对的，就是转成yaml格式就行了

Yaml这个字段注意下，是个字符串
![image](https://github.com/alibaba/ilogtail/assets/13250519/daec940a-3350-417b-bc3d-bf6502d8eba8)

**Comment by yanyanguo** [comment]
@messixukejia 
您好 我按照yaml的格式更改后 如以下图片所示
![image](https://github.com/alibaba/ilogtail/assets/63620024/ef536ef0-0804-4cfa-90dd-61e61f925943)

plugin的log没有关于这个配置文件的报错了 但是我配置是把采集到的metrics输出是写到文件里，没看到有具体的输出文件产生 这个是不是还有问题？
plugin的日志如下图
![image](https://github.com/alibaba/ilogtail/assets/63620024/0a06771d-196e-4693-a27e-1402cc320507)
![image](https://github.com/alibaba/ilogtail/assets/63620024/db497dcf-2f95-43c5-949e-5c7a7f6a3e9c)

**Comment by yanyanguo** [comment]
您好！我按照改为yaml格式的进行配置：



我配置的是输出到文件/和直接输出到标准输出 没看到效果
plugin日志：




能帮我看看是出了什么问题吗


郭漂亮?
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "alibaba/ilogtail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/ilogtail] 如何使用ilogtail开源版本配置采集promethues的数据呢？ (Issue #1380)





 
整体思路是对的，就是转成yaml格式就行了
 
Yaml这个字段注意下，是个字符串
 image.png (view on web)

**Comment by yanyanguo** [comment]
后续改成这个样子可以收集到了
file_out.yaml
enable: true

inputs:

  - Type: service_prometheus

    Yaml: "global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\nscrape_configs:\n  - job_name: \"prometheus\"\n    static_configs:\n      - targets: [\"ip:"port"]"

flushers:

  - Type: flusher_stdout

    OnlyStdout: true
