### ISSUE TITLE
[BUG]:启动报错 Illegal instruction

### ISSUE THREAD

**Issue by 954615673** [alibaba/ilogtail#1399]
**iLogtail Running Environment**
系统信息
Linux k8s-master-1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
cpu信息
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
Stepping:              4
CPU MHz:               1971.313
CPU max MHz:           2000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4000.17
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts spec_ctrl intel_stibp flush_l1d

- ilogtail version:
  ilogtail-2.0.0.linux-amd64.tar.gz

启动报错 Illegal instruction
![微信图片_20240313180017](https://github.com/alibaba/ilogtail/assets/151720977/c66696c1-3d34-46c4-bb42-97ff38a0d4ed)

**Comment by linrunqi08** [comment]
@954615673  问下你们是云环境吗？是哪个云？

**Comment by 954615673** [comment]
一台linux 物理机

**Comment by 954615673** [comment]
> @954615673 问下你们是云环境吗？是哪个云？

如何排查这个问题呢？

**Comment by 954615673** [comment]
> 你可以先用1.8版

好的，谢谢啦！
期待快速更新2.0版本！

**Comment by linrunqi08** [comment]
@954615673  请问一下，你有配置采集配置吗？还是只是启动iLogtail就报错？

**Comment by linrunqi08** [comment]
@954615673  你在社区的群里吗，可以方便加下钉钉或者微信吗

**Comment by 954615673** [comment]
> @954615673 你在社区的群里吗，可以方便加下钉钉或者微信吗
有配置配置文件，我有2台一模一样的操作系统服务器，就这台启动报错，连启动日志都没产生，所以应该没到读取配置文件的流程吧，我理解。
社区群多少我加下，方便加微信的

**Comment by shalousun** [comment]
<img width="1038" alt="image" src="https://github.com/alibaba/ilogtail/assets/9592228/8301292b-6876-4c83-be6c-7faf85a19409"> 测试Intel(R) Xeon(R) CPU E5 v2 系列产品cpu启动会出问题，E5 v4可以启动

**Comment by linrunqi08** [comment]
可以看下这里的结论 https://github.com/alibaba/ilogtail/discussions/1398
