### ISSUE TITLE
[QUESTION]:如何根据不同的路径发送到不同的topic

### ISSUE THREAD

**Issue by beyond688** [alibaba/ilogtail#149]
请问如何将包含A和B和C路径的日志发送到topicX，将包含C和D和E路径的日志发送到topicY，将不包含这些的发送到topicZ。

请问这种场景在自己搭建的iLogtail中该如何配置？

**Comment by EvanLjp** [comment]
建议通过采集配置正则匹配在输入源处区分，声明2份采集配置
