### ISSUE TITLE
[QUESTION]:logtail 如何收集本地或者物理机器上的动态收集文件

### ISSUE THREAD

**Issue by bugCreate** [alibaba/ilogtail#150]
我想要通过logtail 收集物理机器上的动态文件，是否可以不使用logtail 的c端？与c端配合是否必须使用正式发布的

**Comment by EvanLjp** [comment]
物理机器收集文件依赖c部分，此部分正在开源中

**Comment by EvanLjp** [comment]
物理机器收集文件依赖c部分，此部分正在开源中
