### ISSUE TITLE
[FEATURE]:

### ISSUE THREAD

**Issue by bugCreate** [alibaba/ilogtail#151]
我需要收集日志到es

**Comment by EvanLjp** [comment]
目前Logtail不支持输出到es， 如果需要的话，欢迎贡献插件

https://github.com/alibaba/ilogtail/blob/main/docs/zh/guides/README.md

**Comment by EvanLjp** [comment]
目前Logtail不支持输出到es， 如果需要的话，欢迎贡献插件

https://github.com/alibaba/ilogtail/blob/main/docs/zh/guides/README.md
