### ISSUE TITLE
IsValidToSend core dump

### ISSUE THREAD

**Issue by blueskygzhz** [alibaba/ilogtail#1511]
stacktrace:
[pid 3415156] write(3, "signal : 6 \n0x7f5502f94240:  (funlockfile+0x50)\n0x7f5502ab15fb:  (gsignal+0x10b)\n0x7f5502ab2921:  (abort+0x151)\n0x7f5502e73d11:  (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x158)\n0x7f5502e70b27:  (_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE+0xe2)\n0x7f5502e70b4a:  (_ZSt9terminatev+0x11)\n0x7f5502e710b7:  (__cxa_throw+0x79)\n0x7f5502ea632e:  (_ZSt20__throw_out_of_rangePKc+0x4f)\n0x7cec01: 0x7c9835:  (_ZNKSt13unordered_mapIlN7logtail27SingleLogstoreSenderManagerINS0_16SenderQueueParamEEESt4hashIlESt8equal_toIlESaISt4pairIKlS3_EEE2atERS9_+0x23)\n0x7c4e89:  (_ZNK7logtail19LogstoreSenderQueueINS_16SenderQueueParamEE13IsValidToPushEl+0x3f)\n0x830367:  (_ZN13LogtailPlugin13IsValidToSendEx+0x2f)\n0x7f550226623f:  (LogtailIsValidToSend+0x35)\n0x7f54ee423c97:  (_cgo_dd5ea7cf4ecb_Cfunc_LogtailIsValidToSend+0x17)\n0x7f54ec64d061:  (runtime.asmcgocall.abi0+0x61)\n", 872) = 872

![企业微信截图_17169844558920](https://github.com/alibaba/ilogtail/assets/147569085/f373d1ef-7e37-479e-8d59-7e739a970c45)

**Comment by Takuka0311** [comment]
是不是有自己改动过代码？

**Comment by blueskygzhz** [comment]
是的，改了config provider这块的逻辑

**Comment by blueskygzhz** [comment]
有可能，我们先定位下

**Comment by blueskygzhz** [comment]
没同时更新二进制和so导致，先关单了
