### ISSUE TITLE
[DOC]: 文档的这一段好像有错误

### ISSUE THREAD

**Issue by youaodu** [alibaba/ilogtail#1600]
[链接](https://ilogtail.gitbook.io/ilogtail-docs/plugins/input/service-gpu)

service_gpu_metric input插件可以采集 英伟达 GPU 相关指标（如未按照英伟达驱动，此插件无法正常工作）。
这一段话中是打错了吗，按照是安装？

**Comment by messixukejia** [comment]
是打错了，欢迎提个pr改下吧，多谢。
