### ISSUE TITLE
[QUESTION]:Are there docs about ilogtail  demo run on local docker or k8s?

### ISSUE THREAD

**Issue by James601232** [alibaba/ilogtail#162]
ilogtail有没有跑在docker或者k8s上的demo？

**Comment by laotoutou** [comment]
只开源了一部分是吧， 私有化部署是没法用的

**Comment by yyuuttaaoo** [comment]
您好，目前已完整开源。社区版镜像试用请参考：
Kubernetes使用 https://ilogtail.gitbook.io/ilogtail-docs/installation/start-with-k8s
使用DaemonSet模式采集K8s容器日志 https://ilogtail.gitbook.io/ilogtail-docs/getting-started/k8s-daemonset-to-kafka
