### ISSUE TITLE
[QUESTION]:Write json data to kafka failed

### ISSUE THREAD

**Issue by James601232** [alibaba/ilogtail#163]
version:  ilogtail 1.0.31
configruarion:
{

"metrics":
{
    "##1.0##kafka_output_test":
    {
        "category": "file",
        "log_type": "json_log",
        "log_path": "/root/bin/input_data",
        "file_pattern": "json.log",
        "create_time": 1631018645,
        "defaultEndpoint": "",
        "delay_alarm_bytes": 0,
        "delay_skip_bytes": 0,
        "discard_none_utf8": false,
        "discard_unmatch": false,
        "docker_exclude_env":
        {},
        "docker_exclude_label":
        {},
        "docker_file": false,
        "docker_include_env":
        {},
        "docker_include_label":
        {},
        "enable": true,
        "enable_tag": false,
        "file_encoding": "utf8",
        "filter_keys":
        [],
        "filter_regs":
        [],
        "group_topic": "",
        "plugin":
        {
            "flushers":
            [
                    {
                         "type": "flusher_kafka",
                    "detail":
                    {
                        "Brokers":
                        [
                            "192.168.1.1:2181"
                        ],
                        "Topic": "test"
                    }
                    }
            ]
        },
        "local_storage": true,
        "log_tz": "",
        "max_depth": 10,
        "max_send_rate": -1,
        "merge_type": "topic",
        "preserve": true,
        "preserve_depth": 1,
        "priority": 0,
        "raw_log": false,
        "aliuid": "",
        "region": "",
        "project_name": "",
        "send_rate_expire": 0,
        "sensitive_keys":
        [],
        "shard_hash_key":
        [],
        "tail_existed": false,
        "time_key": "",
        "timeformat": "",
        "topic_format": "none",
        "tz_adjust": false,
        "version": 1,
        "advanced":
        {
            "force_multiconfig": false,
            "tail_size_kb": 1024
        }            
    }
}
}

 ilogtail.LOG have following errors:
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/19258506/171116740-86810ab1-39aa-43bb-b171-674aae5ae018.png">

And no data write in kafka

**Comment by linrunqi08** [comment]
Hi James601232, please try to use this config to collect json data to kafka.
{
    "metrics":
    {
        "##1.0##kafka_output_test":
        {
            "category": "file",
            "log_type": "json_log",
            "log_path": "/root/bin/input_data",
            "file_pattern": "json.log",
            "create_time": 1631018645,
            "defaultEndpoint": "",
            "delay_alarm_bytes": 0,
            "delay_skip_bytes": 0,
            "discard_none_utf8": false,
            "discard_unmatch": false,
            "docker_exclude_env":
            {},
            "docker_exclude_label":
            {},
            "docker_file": false,
            "docker_include_env":
            {},
            "docker_include_label":
            {},
            "enable": true,
            "enable_tag": false,
            "file_encoding": "utf8",
            "filter_keys":
            [],
            "filter_regs":
            [],
            "group_topic": "",
            "plugin":
            {
                "processors":
                [
                    {
                        "detail": {
                            "SplitSep": "",
                            "SplitKey": "content"
                        },
                        "type": "processor_split_log_string"
                    },
                    {
                        "detail":
                        {
                            "ExpandConnector": "",
                            "ExpandDepth": 1,
                            "SourceKey": "content",
                            "KeepSource": false
                        },
                        "type": "processor_json"
                    }
                ],
                "flushers":
                [
                    {
                        "type": "flusher_kafka",
                        "detail":
                        {
                            "Brokers":
                            [
                                "localhost:9092"
                            ],
                            "Topic": "logtail-flusher-kafka"
                        }
                    }
                ]
            },
            "local_storage": true,
            "log_tz": "",
            "max_depth": 10,
            "max_send_rate": -1,
            "merge_type": "topic",
            "preserve": true,
            "preserve_depth": 1,
            "priority": 0,
            "raw_log": false,
            "aliuid": "",
            "region": "",
            "project_name": "",
            "send_rate_expire": 0,
            "sensitive_keys":
            [],
            "shard_hash_key":
            [],
            "tail_existed": false,
            "time_key": "",
            "timeformat": "",
            "topic_format": "none",
            "tz_adjust": false,
            "version": 1,
            "advanced":
            {
                "force_multiconfig": false,
                "tail_size_kb": 1024
            }            
        }
    }
}

**Comment by linrunqi08** [comment]
Thanks for your questions. Since you haven't responded for a long time, this issue will be closed. If you have any questions, please open a new issue to tell us.
