### ISSUE TITLE
[QUESTION]写入启用SASL的kafka服务器失败

### ISSUE THREAD

**Issue by sliming** [alibaba/ilogtail#164]
测试kafka的写入，使用不启用任何安全认证的kafka，按照样例，能正常写入。

而另一个kafka集群带安全认证，flusher里设置了SASLUsername，SASLPassword，但是写入失败。
logtail_plugin.LOG 里报错 error:kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
此集群的要求设置 
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
这样的情况该如何在flusher中设置呢？

另外，ilogtail的相关文档和案例过于缺少。

**Comment by messixukejia** [comment]
logtail的kafka flusher是基于https://github.com/Shopify/sarama实现的，如需要扩展参数，欢迎贡献代码共建。 
初步看扩展下对应代码的参数即可：https://github.com/alibaba/ilogtail/blob/main/plugins/flusher/kafka/flusher_kafka.go#L61

logtail主要的文档是在阿里云官网上的，https://help.aliyun.com/document_detail/95923.html，配合SLS使用提供了丰富的文档案例说明。开源相关的文档相对少一些，logtail C++部分预计下月会开源，会有一些列的开源社区的建设。

**Comment by sliming** [comment]
看过这个源代码，就是从里面找到的SASLUsername，SASLPassword两个参数，但是没有看到sasl.mechanism，是不是得自己修改源代码了？

阿里云官网的文档看了，没那些文档更没法玩了，好多内容是配合阿里云服务的，有图形界面，而开源的没有，也没有SLS。

**Comment by messixukejia** [comment]
> 看过这个源代码，就是从里面找到的SASLUsername，SASLPassword两个参数，但是没有看到sasl.mechanism，是不是得自己修改源代码了？
> 
> 阿里云官网的文档看了，没那些文档更没法玩了，好多内容是配合阿里云服务的，有图形界面，而开源的没有，也没有SLS。

需要扩展下参数：https://github.com/alibaba/ilogtail/blob/main/vendor/github.com/Shopify/sarama/config.go#L67
kafka的flusher是社区贡献的，可以自己修改下，给我们发pr。

**Comment by messixukejia** [comment]
本QUESTION issue先关闭了，后续如果提交代码可以新建一个feature的issue。多谢

**Comment by ZLfen** [comment]
> 测试kafka的写入，使用不启用任何安全认证的kafka，按照样例，能正常写入。
> 
> 而另一个kafka集群带安全认证，flusher里设置了SASLUsername，SASLPassword，但是写入失败。 logtail_plugin。LOG 里报错 error：kafka： client has run out of available brokers to talk to （Is your cluster reachable？） 此集群的要求设置 security.protocol=SASL_PLAINTEXT sasl.mechanism=SCRAM-SHA-256 这样的情况该如何在flusher中设置呢？
> 
> 另外，ilogtail的相关文档和案例过于缺少。

您好，请问下你这个最终是怎么解决的，我也遇到了这个问题，
![f09519e79d5bfe80605dcab868f2787d](https://github.com/user-attachments/assets/8b71a999-3746-46b6-9fe7-f2968ac10aed)

**Comment by ZLfen** [comment]
> > 测试kafka的写入，使用不启用任何安全认证的kafka，按照样例，能正常写入。
> > 而另一个kafka集群带安全认证，flusher里设置了SASLUsername，SASLPassword，但是写入失败。logtail_plugin。LOG 里报错 error：kafka： client has run out of available brokers to talk to （Is your cluster reachable？此集群的要求设置 security.protocol=SASL_PLAINTEXT sasl.mechanism=SCRAM-SHA-256 这样的情况该如何在flusher中设置呢？
> > 另外，ilogtail的相关文档和案例过于缺少。
> 
> 您好，请问下你这个最终是怎么解决的，我也遇到了这个问题， ![f09519e79d5bfe80605dcab868f2787d](https://private-user-images.githubusercontent.com/100279863/375914795-8b71a999-3746-46b6-9fe7-f2968ac10aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTcxMDEsIm5iZiI6MTcyODY5NjgwMSwicGF0aCI6Ii8xMDAyNzk4NjMvMzc1OTE0Nzk1LThiNzFhOTk5LTM3NDYtNDZiNi05ZmU3LWYyOTY4YWMxMGFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMTMzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDZjNGVhM2UwNjBkZGM2YzU0NjQ4N2QyOGRlOWVkNTYwNmM2MmMwMTM2YzQwY2E1ZmY5ZWQ2YWM5NTJkNDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u4jyBUUZxuXjUrMPvjki8jevytBO0zZ7ld7k8T5u5hU)

采集配置文件：
![image](https://github.com/user-attachments/assets/e28ee9a9-2aea-48ec-ac6c-2e3bd903875d)
