### ISSUE TITLE
[QUESTION]:中文帮助文档，各种文档地址都打不开啊，谁能看看呢

### ISSUE THREAD

**Issue by lifei64** [alibaba/ilogtail#1650]
中文帮助文档，各种文档地址都打不开啊，谁能看看呢

**Comment by Takuka0311** [comment]
文档链接：https://ilogtail.gitbook.io/ilogtail-docs

由于特殊国情，gitbook在境内访问可能不稳定，可以尝试：

1. 使用VPN或代理服务器
2. 更换DNS服务器
3. 查看离线文档。ilogtail的中文文档在代码仓库的[docs/cn](https://github.com/alibaba/ilogtail/tree/main/docs/cn)目录下

**Comment by lifei64** [comment]
我使用了代理访问，打不开这个链接， 我先看离线文档了，多谢
