### ISSUE TITLE
[FEATURE]: Open Source Cpp Core

### ISSUE THREAD

**Issue by yyuuttaaoo** [alibaba/ilogtail#176]
**Concisely describe the proposed feature**
Open source cpp core
Enable ilogtail plugin to run with main C++ program.

**Describe the solution you'd like (if any)**
Run ilogtail on host.
Run ilogtail in container.
Run ilogtail in K8s.

**Additional comments**
A brief doc to introduce C++ core.

**Comment by dirtyA** [comment]
When will open source code this year?
