### ISSUE TITLE
[QUESTION]: 请问下现在C++开源部分的哪个版本是C++的可用版本吗？

### ISSUE THREAD

**Issue by JeffPhoneix** [alibaba/ilogtail#189]

**Comment by messixukejia** [comment]
一些内容还在准备中，这几天会把版本包做出来，并且会做一些宣传。麻烦再等两天。

**Comment by yyuuttaaoo** [comment]
您好，当前1.1.0的release已发布。
binary下载：https://ilogtail.gitbook.io/ilogtail-docs/installation/release-notes
source：https://github.com/alibaba/ilogtail/releases
