### ISSUE TITLE
[QUESTION]: 咨询下贵司，https://github.com/alibaba/ilogtail，ilogtail目前支持output http协议到自己开发的接口？

### ISSUE THREAD

**Issue by lovek8s** [alibaba/ilogtail#197]
咨询下贵司，https://github.com/alibaba/ilogtail，ilogtail目前支持output http协议到自己开发的接口？

**Comment by messixukejia** [comment]
目前ilogtail支持的flusher还不是太多，列表在这里https://github.com/alibaba/ilogtail/tree/main/plugins/flusher

如果需要欢迎贡献插件，我们也会提供必要的支持。
