### ISSUE TITLE
[QUESTION]:Why frequently use util.RandomSleep? 

### ISSUE THREAD

**Issue by JeffPhoneix** [alibaba/ilogtail#199]
LogFileReader 的run协程中， 使用 util.RandomSleep 这种休眠是为了解决什么问题吗？
我猜想是为了实现某种读取磁盘文件的时间片机制，防止某一个LogConfig下的大量文件读取完全占据磁盘带宽，而影响其他LogConfig的读取吗？保证不同采集配置间的公平性？

**Comment by EvanLjp** [comment]
主要的处理逻辑在processor process 里,会一直读到文件无换行符,之后会进行sleep 操作,仅仅是一般避免浪费CPU 的考虑, 这部分代码有部分每个文件独立协程,在内存优化方面,如重用对象BLock,以及尽可能避免拷贝等来节省CPU 消耗, 达到在单行采集下逼近CPP部分代码的效率
