### ISSUE TITLE
[FEATURE]: iLogtail support Elasticsearch Flusher.

### ISSUE THREAD

**Issue by liupanhu** [alibaba/ilogtail#202]
Concisely describe the proposed feature
FileBeat and FluentBit can forward data to Elastic Search directly. If the data collected is not too big, it is preferred to write data into ES directly. I want iLogtail to support this feature.

Describe the solution you'd like (if any)
Write an ElasticSearch flusher named flusher_elastic_search.

Additional comments
Reference configuration at FluentBit: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

**Comment by messixukejia** [comment]
不支持，欢迎贡献代码。需要我们协助的话，可以加下钉钉群，提一下这个issue。

**Comment by joeCarf** [comment]
Plz assign it to me :)
