### ISSUE TITLE
[BUG]:LogPath 为软连目录收集不到日志

### ISSUE THREAD

**Issue by zy14** [alibaba/ilogtail#205]
nginx_log.yaml: |
    enable: true
    inputs:
      - Type: file_log
        LogPath: /data/logs/
        FilePattern: "*.log"
        DockerFile: true

**Comment by yyuuttaaoo** [comment]
目前，容器场景使用Daemonset方式不支持软连接采集，商业版目前也有这个限制。
这种情况往往是原来使用sidecar或者直接从主机上采集文件迁移过来碰到的。
使用Daemonset方式，请直接采集容器内的源路径。

**Comment by zy14** [comment]
LogPath: /data/logs/  支持环境变量的方式么，因为log目录是按照pod name生成的

**Comment by zy14** [comment]
metadata.name 这种的
