### ISSUE TITLE
[BUG]:host meta  yaml  doesnot work

### ISSUE THREAD

**Issue by liyuefu** [alibaba/ilogtail#207]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.
collect host meta data with metric_meta_host does not work.

**To Reproduce**
Please post your configurations and environments to reproduce the bug.
----
enable: true
inputs:
  - Type: metric_meta_host
    CPU: true
    Memory: false
    Net: false
    Disk: false
    Process: false
    ProcessIntervalRound: 60
    ProcessNamesRegex:
      - ilogtail
    Labels:
      cluster: ilogtail-test-cluster
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
----
start ilogtail.
error in ilogtail.LOG

[2022-07-22 21:20:28.224154]	[error]	[015305]	/src/core/plugin/LogtailPlugin.cpp:490		init plugin base error:1

The developer team will put a higher priority on bugs that can be reproduced. If you want a prompt reply, please keep your descriptions  **detailed**.

- Your ilogtail version:
- 1.1.0

- Your platform:
- linux

- Your configuration:
- enable: true
inputs:
  - Type: metric_meta_host
    CPU: true
    Memory: false
    Net: false
    Disk: false
    Process: false
    ProcessIntervalRound: 60
    ProcessNamesRegex:
      - ilogtail
    Labels:
      cluster: ilogtail-test-cluster
flushers:
  - Type: flusher_stdout
    OnlyStdout: true

- Your ilogtail logs:
- [2022-07-22 21:20:28.224154]	[error]	[015305]	/src/core/plugin/LogtailPlugin.cpp:490		init plugin base error:1

**Additional comments**
If possible, please also consider attaching the output of [ilogtail diagnose tool](https://help.aliyun.com/document_detail/52578.htm?spm=a2c4g.11186623.0.0.4d254a9cAvG8ls#concept-q2t-pqb-dfb). This produces detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by messixukejia** [comment]
给一下：
1、ilogtail_config.json

2、user_yaml_config.d下的所有文件配置

**Comment by liyuefu** [comment]
我在清理yaml文件时,把其它文件移走后, 运行正常.
把移走的文件移回来,也正常. 

[nome@linux7-mysql-sandbox ilogtail-1.1.0]$ cat ilogtail_config.json 
{
}

**Comment by messixukejia** [comment]
完整配置都发下看看

**Comment by messixukejia** [comment]
现在是正常还是有问题？

如果有问题，2、user_yaml_config.d下的所有文件配置。都发下

**Comment by messixukejia** [comment]
另外也可以看下logtail_plugin.LOG日志

**Comment by liyuefu** [comment]
现在正常. 谢谢.
我做的操作就是清理了没有用的yaml文件(enable:  false), 启动就好了.
再移回来时也正常. 
谢谢. 可以关闭了.
