### ISSUE TITLE
[BUG]:ilogtail启动失败

### ISSUE THREAD

**Issue by chllcy** [alibaba/ilogtail#209]
运行平台：arm64
运行版本：1.0.30

现象：system启动之后只看到一个ilogtail进程，正常都是2个,启动之后会存在时间跳变(可能向前跳变，也可能向后跳变)，不知道是否有影响？进系统后restart service又正常了，var/log/syslog里没看到错误

● bmilogtail.service - ilogtail service
   Loaded: loaded (/lib/systemd/system/bmilogtail.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-12-10 17:15:55 CST; 7 months 13 days ago
 Main PID: 1284 (ilogtail)
    Tasks: 1 (limit: 3217)
   CGroup: /system.slice/bmilogtail.service
           └─1284 /var/ilogtail/ilogtail

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.`

**Comment by panawala** [comment]
麻烦确认下用的阿里云SLS(日志服务)的ilogtail吗？

如果是，可以看下/usr/local/ilogtail/ilogtail.LOG的日志；

**Comment by chllcy** [comment]
你好 用的就是GitHub上的1.0.30版本(arm64版本)，传到SLS上
我这里没有/usr/local/ilogtail/目录呢，另外系统时间跳变到2023年，进程都起来了，但是日志没有传到SLS上。

● bmilogtail.service -  ilogtail service
   Loaded: loaded (/lib/systemd/system/bmilogtail.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-03-09 02:53:05 CST; 7 months 13 days left
  Process: 1270 ExecStart=/var/ilogtail/ilogtail (code=exited, status=0/SUCCESS)
 Main PID: 1310 (ilogtail)
    Tasks: 17 (limit: 3217)
   CGroup: /system.slice/bmilogtail.service
           ├─1310 /var/ilogtail/ilogtail
           └─1313 /var/ilogtail/ilogtail

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by panawala** [comment]
这边的用法看起来是商业版的Logtail？建议直接在SLS控制台使用，https://help.aliyun.com/document_detail/28979.html；

**Comment by chllcy** [comment]
> 

用的就是社区版ilogtail呢，只是传到SLS，只是配置用官方的吧

**Comment by panawala** [comment]
官方有ARM版支持，https://help.aliyun.com/document_detail/28982.html；也可以进下文档中的钉钉群，支持比较方便

**Comment by yyuuttaaoo** [comment]
closed as timeout
