### ISSUE TITLE
[FEATURE]: iLogtail support Loki Flusher.

### ISSUE THREAD

**Issue by messixukejia** [alibaba/ilogtail#259]
**Concisely describe the proposed feature**
I would like to add an Loki flusher plugin to send data to Loki server.

**Describe the solution you'd like (if any)**
We can use the package `https://github.com/grafana/loki-client-go` to act with Loki server.

**Comment by hehua2018** [comment]
请问ilogtail日志输出到loki服务器功能怎么使用，谢谢

**Comment by messixukejia** [comment]
暂不支持，欢迎参与恭喜。如果可以开发，可以群里联系我们一起交流下

**Comment by Abingcbc** [comment]
I would like to do this :)

**Comment by messixukejia** [comment]
![image](https://user-images.githubusercontent.com/13250519/220599556-15f2ac20-47a2-459a-aab8-41d4ed09f17c.png)
可以参考下这些实现
