### ISSUE TITLE
[FEATURE]: iLogtail support Elasticsearch Flusher

### ISSUE THREAD

**Issue by yyuuttaaoo** [alibaba/ilogtail#261]
**Concisely describe the proposed feature**
FileBeat and FluentBit can forward data to Elastic Search directly. If the data collected is not too big, it is preferred to write data into ES directly. I want iLogtail to support this feature.

**Describe the solution you'd like (if any)**
Write an ElasticSearch flusher named flusher_elastic_search.

**Additional comments**
Reference configuration at FluentBit: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

**Comment by messixukejia** [comment]
Same to #202
