### ISSUE TITLE
金山云kubernetes集群获取日志失败

### ISSUE THREAD

**Issue by xunmeng-666** [alibaba/ilogtail#27]
金山云docker默认数据存储在/data/docker/下。 使用ilogtail 获取docker标准输出失败时，无法获取到日志文件。 
<img width="783" alt="docker_path" src="https://user-images.githubusercontent.com/14903429/144535641-5ea31650-7829-4ceb-a16c-be9d49f55043.png">

**Comment by ermazi** [comment]
不会吧不会吧，应该是使用问题吧

**Comment by EvanLjp** [comment]
Maybe history version bug, already provide new version package.
Close first, looking forward to a reply.
