### ISSUE TITLE
[BUG]: A possible leak when dlsym fails

### ISSUE THREAD

**Issue by TDAkory** [alibaba/ilogtail#340]
**Describe the bug**
When dlsym fails, close wrong pointer of shared library as **pointer mismatch**

**iLogtail Running Environment**
Please provide the following information: 

- ilogtail version: 
  - dlopen with `mPluginAdapterPtr` : https://github.com/alibaba/ilogtail/blob/main/core/plugin/LogtailRuntimePlugin.cpp#L98
  - dlclose with `mPluginBasePtr` when add symbol fails : https://github.com/alibaba/ilogtail/blob/main/core/plugin/LogtailRuntimePlugin.cpp#L109
  
- Yaml configuration:

- ilogtail.LOG:

- logtail_plugin.LOG:

**Comment by messixukejia** [comment]
Thanks a lot for helping to find this bug. The code in this place is not the main working mode for ilogtail, so it will not be executed and will not cause a big risk of leakage.

Is it possible for you to submit a PR to fix this bug? Thanks.

**Comment by TDAkory** [comment]
Sure, I will submit a PR this weekend

**Comment by messixukejia** [comment]
Thanks for your contributing.

**Comment by messixukejia** [comment]
Thanks for your contributing. Could you  contact with me for further discussion?

![image](https://user-images.githubusercontent.com/13250519/187113876-a67ea324-e648-4315-8698-f4c1adde0e88.png)
