### ISSUE TITLE
[QUESTION]:是否会长期维护

### ISSUE THREAD

**Issue by juewu4072** [alibaba/ilogtail#37]
几年前有个[log-pliot](https://github.com/AliyunContainerService/log-pilot)后续就无人维护，想了解一下ilogtail这个项目后续维护计划

**Comment by EvanLjp** [comment]
1. This project is an LTS project.
2. iLogtail has been running in alibaba group nearly 8 years.
3. In alibaba cloud, our project is called SLS, a.k.a LogService, ten thousands of users need it as an LTS project.

**Comment by EvanLjp** [comment]
https://help.aliyun.com/product/28958.html
