### ISSUE TITLE
[FEATURE]:  守护进程 

### ISSUE THREAD

**Issue by XLPE** [alibaba/ilogtail#397]
Concisely describe the proposed feature：
目前ilogtail是单进程多线程程序。当CPU和内存超出限制后，进程会自动退出。

Describe the solution you'd like (if any)
设计父子进程，每隔5秒检测一下【子进程】状态，如果【子进程】异常退出，父进程会自动拉起子进程。

**Comment by yyuuttaaoo** [comment]
这个问题应可以通过daemontools（http://cr.yp.to/daemontools.html）或者supervised（http://supervisord.org/）之类的工具解决。后面可以搞一个案例。

**Comment by jcy1001** [comment]
这个守护进程的工具确认非常重要 ，需要windows的和linux版本的

**Comment by messixukejia** [comment]
> 这个守护进程的工具确认非常重要 ，需要windows的和linux版本的

如果有兴趣，可以一起来开发下，我们提供支持，欢迎认领下这个issue

**Comment by pj1987111** [comment]
I would like to do this

**Comment by linrunqi08** [comment]
@pj1987111   I'm glad you're willing to claim this feature. I will assign this feature to you.
