### ISSUE TITLE
[FEATURE]: Bump Go version to 1.19.1

### ISSUE THREAD

**Issue by szy441687879** [alibaba/ilogtail#415]
go在1.19增加了一个新特性，[soft-memory-limit](https://github.com/golang/proposal/blob/master/design/48409-soft-memory-limit.md)
感觉特别适用于日志这种对象创建新建和销毁比较频繁的场景，在我这边单实例100Mb/s的场景下大概有20-30%的性能提升
说明:对比场景未使用Go ballast和SetGCPercent进行gc优化。
通过这个设置应该也可以解决这段代码中提到的问题
[`setGCPercentForSlowStart `](https://github.com/alibaba/ilogtail/blob/9a36feec37fc14ad516df6dc1a93c1e550c13cf3/plugin_main/plugin_export.go#L245)

**Comment by messixukejia** [comment]
等1.19多出几个小版本后，我们跟进下

**Comment by szy441687879** [comment]
嗯，当前我们线上运行的是1.19，上千个实例，暂时比较稳定，没出啥问题，可以多观察下

**Comment by yyuuttaaoo** [comment]
需要更新这些go.mod，并更新编译镜像中的go版本
![image](https://github.com/alibaba/ilogtail/assets/1827594/13764dd8-03df-4de1-acef-1f18158d2153)
