### ISSUE TITLE
[FEATURE]:support http and https flusher

### ISSUE THREAD

**Issue by totticarter** [alibaba/ilogtail#450]
ilogtail支持http flusher
1. 支持POST日志到配置项中的http服务器
2. 支持https协议
3. 支持采集配置项下发和批量修改
4. 支持机器组通过tag识别和心跳管理

**Comment by messixukejia** [comment]
暂时无计划，如果需要可以欢迎参与贡献。加入钉钉群@下 徐可甲，可以先一起交流下。

**Comment by totticarter** [comment]
> 暂时无计划，如果需要可以欢迎参与贡献。加入钉钉群@下 徐可甲，可以先一起交流下。

请问钉钉群是哪个？

**Comment by messixukejia** [comment]
![image](https://user-images.githubusercontent.com/13250519/194855099-a1105a74-aa58-4801-a023-fd41a5090ad9.png)

**Comment by totticarter** [comment]
![image](https://user-images.githubusercontent.com/7816312/196356601-fa72301c-99c4-4d39-89bb-a0230eda3fba.png)

**Comment by liuhaoyang** [comment]
在 PR https://github.com/alibaba/ilogtail/pull/521 已支持HTTP flusher  by @snakorse
