### ISSUE TITLE
支持通过接口下发采集数据？

### ISSUE THREAD

**Issue by melin** [alibaba/ilogtail#54]
支持通过接口下发采集数据？以及暂停和终止等操作，可以通过接口下发新增采集需求。

**Comment by shabicheng** [comment]
采集配置接口管理需要一个集中式的ConfigService，这个默认iLogtail就是支持的，依托阿里云上的SLS实现。具体的接口可以参考：https://help.aliyun.com/document_detail/29042.html
SDK有Java、Golang、Python

https://help.aliyun.com/document_detail/29063.html

**Comment by melin** [comment]
iLogtail 开源版本支持？不依赖SLS

shabicheng ***@***.***> 于2021年12月21日周二 09:50写道：

**Comment by EvanLjp** [comment]
There is an http interface for E2E test. https://github.com/alibaba/ilogtail/blob/main/main/plugin_http.go
I am worried about that way cannot meet your needs.  But Configservice is not an opensource project. So We can't provide that capability. 
If you want to use it, please use the LogService with commercial version.
