### ISSUE TITLE
[FEATURE]: kafka input插件支持高版本的kafka client

### ISSUE THREAD

**Issue by shalousun** [alibaba/ilogtail#600]
**Concisely describe the proposed feature**
kafka input插件依赖`github.com/bsm/sarama-cluster`的库已经被放弃维护，历史原因是sarama不支持consumer group，但是新的sarama已经支持consumer group。当前只用的sarama-cluster也就是限制出了sarama无法升级，升级后无法编译通过，如果用户有高于kafka 2.7版本服务都无法支持。去掉zk依赖的高版本kafka未来也会企业升级落地的主流

最新的版本中因为vendor剔除，原始修改sarama-cluster中代码bug的https://github.com/alibaba/ilogtail/pull/472  也丢了，#471 提到的问题新版本仍然被带了回来，因此目前看也是需要升级修改的。
**Describe the solution you'd like (if any)**
在当前不更换kafka sarama这个客服端的情况下，直接采用sarama高版本的api实现kafka input，改动不基本不涉及到对外的用户配置改动。
实现时需要主要参考官方的https://github.com/Shopify/sarama/blob/main/examples/consumergroup/main.go
代码，尤其是里面的下面代码片段需要注意，否则可能导致rebanlance无法被感知到
```
go func() {
		defer wg.Done()
		for {
			// `Consume` should be called inside an infinite loop, when a
			// server-side rebalance happens, the consumer session will need to be
			// recreated to get the new claims
			if err := client.Consume(ctx, strings.Split(topics, ","), &consumer); err != nil {
				log.Panicf("Error from consumer: %v", err)
			}
			// check if context was cancelled, signaling that the consumer should stop
			if ctx.Err() != nil {
				return
			}
			consumer.ready = make(chan bool)
		}
	}()
```
**Additional comments**

**Comment by codingdancer** [comment]
我是 https://github.com/alibaba/ilogtail/issues/471 报告者，在新版本vendor删除的 情况也有另外一种解决方式，修改sarama的版本：
gomod 的配置改下版本号就可以
github.com/Shopify/sarama v1.24.1
github.com/bsm/sarama-cluster v2.1.15+incompatible
