### ISSUE TITLE
[QUESTION]: Build iLogtail project failed

### ISSUE THREAD

**Issue by cuiqingqing** [alibaba/ilogtail#62]
Envoriment:
Centos 7
go version go1.17.5 linux/amd64

Openration:
1. Pull iLogtail code
2. build the project with command: make vendor && make build
3. get build like below, could you help check the reason?
=============================================
root@node2:~/workingcui/iLogtail/git/ilogtail(main)]make vendor && make build
rm -rf license_coverage.txt
...
rm -rf vendor
go mod vendor
./external/sync_vendor.py
execute cmd cp -r /root/workingcui/iLogtail/git/ilogtail/external/github.com /root/workingcui/iLogtail/git/ilogtail/external/../vendor/: 0
execute cmd cp -r /root/workingcui/iLogtail/git/ilogtail/external/README.md /root/workingcui/iLogtail/git/ilogtail/external/../vendor/: 0
rm -rf license_coverage.txt
...
rm -rf find_licenses
./scripts/build.sh vendor default
Linux

vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:33: fatal error: systemd/sd-journal.h: No such file or directory
 // #include <systemd/sd-journal.h>
                                 ^
compilation terminated.
make: *** [build] Error 2

=============================================
![image](https://user-images.githubusercontent.com/26838327/147521515-8de222de-453b-43e1-87ee-3a33b697a648.png)

**Comment by EvanLjp** [comment]
yum install systemd-devel
