### ISSUE TITLE
[FEATURE]: Enhance addfields processor to dynamic read env value

### ISSUE THREAD

**Issue by EvanLjp** [alibaba/ilogtail#63]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example,
> I would like to enhance addfields feature to dynamic read env value rather current fixed value.

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement. For example,
> enhance https://github.com/alibaba/ilogtail/tree/main/plugins/processor/addfields plugin.

**Comment by EvanLjp** [comment]
or append processor

**Comment by EvanLjp** [comment]
1. support to add dynamic value for [addfields](https://github.com/alibaba/ilogtail/tree/main/plugins/processor/addfields) processor or [appended](https://github.com/alibaba/ilogtail/tree/main/plugins/processor/appender) processor

**Comment by xmapst** [comment]
> 

第二点是不是这个效果
![image](https://user-images.githubusercontent.com/36829716/157148099-a42a386c-c9bd-49e6-8fe9-bcab31c7b160.png)
