### ISSUE TITLE
[BUG]: 关于ConfigServer的问题

### ISSUE THREAD

**Issue by CyshallChan** [alibaba/ilogtail#691]
**Describe the bug**
文档中提供的配置文件：
```json
{
    ...
    "ilogtail_configserver_address" : [
      "127.0.0.1:8899"
      ],
    ...
}
```

根据`AppConfig::LoadAddrConfig`函数中的代码，这个json根本不符合判断逻辑：

```cpp
// 首先根据提供的json来说，应该判断confJson["ilogtail_configserver_address"]是否是数组，而不是对象
if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
        Json::Value::Members members = confJson["ilogtail_configserver_address"].getMemberNames();
        for (Json::Value::Members::iterator it = members.begin(); it != members.end(); it++) {
            vector<string> configServerAddress = SplitString(TrimString(confJson["ilogtail_configserver_address"][*it].asString()), ":");
            ......
        }
        LOG_INFO(sLogger, ("ilogtail_configserver_address", confJson["ilogtail_configserver_address"].toStyledString()));
    }
```

随后将json改成如下，可以通过判断逻辑：

```json
{
  "ilogtail_configserver_address" :{ "a" :"127.0.0.1:8899"} 
}
```

但随后验证IP的正则表达式又出现了问题：

```cpp
   if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
        Json::Value::Members members = confJson["ilogtail_configserver_address"].getMemberNames();
        for (Json::Value::Members::iterator it = members.begin(); it != members.end(); it++) {
            ......
            // 正则有问题，无法判断IPv4地址
            boost::regex reg_ip = boost::regex(" (?:(?:1[0-9][0-9]\\.)|(?:2[0-4][0-9]\\.)|(?:25[0-5]\\.)|(?:[1-9][0-9]\\.)|(?:[0-9]\\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9])|(?:[0-9]))");      
        	......
        }
        LOG_INFO(sLogger, ("ilogtail_configserver_address", confJson["ilogtail_configserver_address"].toStyledString()));
    }
```

后改成如下正确：

```cpp
"(?:(?:1[0-9][0-9]\.)|(?:2[0-4][0-9]\.)|(?:25[0-5]\.)|(?:[1-9][0-9]\.)|(?:[0-9]\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9])|(?:[0-9]))"
```

此时根据逻辑，configserver所需的IP和端口已经被送进了`mConfigServerAddresses`中，在随后的发送心跳的逻辑中又出现了诡异的问题，代码在`ConfigManager::CheckUpdateThread`函数中：

```cpp
        if (curTime - lastCheckTime >= checkInterval) {
            // 诡异问题出现在这里，configServerAddress对象中的IP是正常的，但是端口是一个类似‘-3254252345’这种负数，给人的感觉是被销毁了
            AppConfig::ConfigServerAddress configServerAddress = AppConfig::GetInstance()->GetOneConfigServerAddress(false);
            if ("" != configServerAddress.host) {
                ......
                // 因为前面端口出现了问题，因此这边自然也发送不了心跳
                checkResults = SendHeartbeat(configServerAddress);
                ......
        }

```

随后我在想是不是因为`GetOneConfigServerAddress`函数返回常量引用的问题，但是在C++中常量引用可以延长临时变量的生命周期啊，死亡当活马医，我将`GetOneConfigServerAddress`函数改成了值返回：

```cpp
AppConfig::ConfigServerAddress AppConfig::GetOneConfigServerAddress(bool changeConfigServer)
```

然后获取端口就正常了，随后发送心跳正常了，在ConfigServer中的日志也能看到访问日志打印出来了：
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/22564041/222628352-170c0907-08d1-410a-9321-1d075e09a204.png">

但此时在发送心跳函数`ConfigManager::SendHeartbeat`中又出现了另外一个问题：

```cpp
try {
        // client.Send函数返回异常导致程序崩溃
        client.Send(sdk::HTTP_POST,
                    configServerAddress.host,
                    configServerAddress.port,
                    operation,
                    "",
                    httpHeader,
                    reqBody,
                    INT32_FLAG(sls_client_send_timeout),
                    httpResponse,
                    "",
                    false
        );
        configserver::proto::HeartBeatResponse heartBeatResp;
        heartBeatResp.ParseFromString(httpResponse.content);

        if (0 != strcmp(heartBeatResp.request_id().c_str(), requestID.c_str())) return emptyResult;

        LOG_DEBUG(sLogger, ("SendHeartBeat","success")("reqBody", reqBody)
                  ("requestId", heartBeatResp.request_id())("statusCode", heartBeatResp.code()));

        return heartBeatResp.pipeline_check_results();
    } catch (const sdk::LOGException& e) {
        LOG_WARNING(sLogger, ("SendHeartBeat", "fail")("reqBody", reqBody)("errCode", e.GetErrorCode())("errMsg", e.GetMessage()));
        return emptyResult;
    }
```
<img width="483" alt="image" src="https://user-images.githubusercontent.com/22564041/222628386-76341470-a8b9-4a1e-a811-210f4993025c.png">

环境是用的官方提供的开发镜像。

最后，因为本人已经许久没写c++了，好多东西都忘了，排错起来比较耗时再加上最近比较忙，希望官方人员可以帮忙瞅瞅到底是啥问题。

# 

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version:
main分支的代码和1.3.1版本都尝试过
  
- Yaml configuration:

- ilogtail.LOG:
[崩溃日志](https://paste.org.cn/r3ypcAdLSZ)

- logtail_plugin.LOG:

**Comment by CyshallChan** [comment]
这个`client.Send()` 造成的崩溃我这边解决了，但是出现了个新崩溃，具体可以看调试的截图：
<img width="2242" alt="image" src="https://user-images.githubusercontent.com/22564041/224210016-1b093f15-5d85-48b6-a55e-8a423754989e.png">

真得很奇怪，return之后因该返回上一层了，结果跑回之前的位置。

崩溃日志：
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/22564041/224213396-eb5ad898-7445-47c2-a560-c90a71a20a62.png">

详细崩溃日志：
https://paste.org.cn/yghxcEr39x

想问下有什么进展吗？另外Agent ConfigServer的问题我有兴趣解决，但是我需要一些帮助。

**Comment by Takuka0311** [comment]
> 这个`client.Send()` 造成的崩溃我这边解决了，但是出现了个新崩溃，具体可以看调试的截图： <img alt="image" width="2000" src="https://user-images.githubusercontent.com/22564041/224210016-1b093f15-5d85-48b6-a55e-8a423754989e.png">
> 
> 真得很奇怪，return之后因该返回上一层了，结果跑回之前的位置。
> 
> 崩溃日志： <img alt="image" width="1166" src="https://user-images.githubusercontent.com/22564041/224213396-eb5ad898-7445-47c2-a560-c90a71a20a62.png">
> 
> 详细崩溃日志： https://paste.org.cn/yghxcEr39x
> 
> @yyuuttaaoo @Takuka0311 想问下有什么进展吗？另外Agent ConfigServer的问题我有兴趣解决，但是我需要一些帮助。

感谢您的反馈！您提出的问题我将在近几天检查并尝试修复，届时将与您实时同步进展；如果您有兴趣解决这个问题，我非常乐意协助您，您可以列出需要帮助的点，我会尽力解答

**Comment by CyshallChan** [comment]
@Takuka0311 你们提供的开发镜像中如何生成coredump文件，我搜了很多答案都无效。

**Comment by Takuka0311** [comment]
> 

您是指多次尝试在容器中生成coredump失败吗？

**Comment by Takuka0311** [comment]
> @Takuka0311 你们提供的开发镜像中如何生成coredump文件，我搜了很多答案都无效。

您是指多次尝试在容器中生成coredump失败了吗？

**Comment by CyshallChan** [comment]
> > @Takuka0311 你们提供的开发镜像中如何生成coredump文件，我搜了很多答案都无效。
> 
> 您是指多次尝试在容器中生成coredump失败了吗？

对的。

**Comment by yyuuttaaoo** [comment]
> @Takuka0311 你们提供的开发镜像中如何生成coredump文件，我搜了很多答案都无效。
运行的时候加一个参数 -ilogtail_disable_core=false

/usr/local/ilogtail/ilogtail --help | grep core
    -cpu_usage_up_limit (cpu usage upper limit, cores) type: double default: 2
    -pub_cpu_usage_up_limit (cpu usage upper limit, cores) type: double
    -ilogtail_disable_core (disable core in worker process) type: bool

**Comment by CyshallChan** [comment]
> > @Takuka0311 你们提供的开发镜像中如何生成coredump文件，我搜了很多答案都无效。
> > 运行的时候加一个参数 -ilogtail_disable_core=false
> 
> /usr/local/ilogtail/ilogtail --help | grep core -cpu_usage_up_limit (cpu usage upper limit, cores) type: double default: 2 -pub_cpu_usage_up_limit (cpu usage upper limit, cores) type: double -ilogtail_disable_core (disable core in worker process) type: bool

@yyuuttaaoo @Takuka0311 关闭这个选项依然没有coredump生成，我看了下代码就是设置soft和hard的limit，以下是我的操作过程：
首先将开发镜像设置unlimited：
<img width="427" alt="image" src="https://user-images.githubusercontent.com/22564041/224670615-c95fe08a-5f38-4679-9c4c-e186451cb304.png">

接着gdb调试启动并设置ilogtail_disable_core为false，代码也确实走了enable_core()函数
<img width="776" alt="image" src="https://user-images.githubusercontent.com/22564041/224672498-92a4fd93-8bf7-4be4-9382-ef277b941946.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/22564041/224672437-fe673faa-e8e9-4bd4-ab9b-c23fcd79585d.png">
依然没有生成coredump

**Comment by Takuka0311** [comment]
我提交了一版解决方案 https://github.com/alibaba/ilogtail/pull/703 ，您可以查看一下。解析地址的问题感谢您指出来，已经更正；client.Send()造成崩溃的原因已经定位到了，SendHeartbeat函数中将AgentAttributes添加到HeartBeatRequest的方式使用的是set_allocated_attributes方法，而这在proto3中不能被很好的支持，造成了内存问题，修改为MergeFrom方法后，经过测试已经可以正常发送心跳

**Comment by CyshallChan** [comment]
> 我提交了一版解决方案 https://github.com/alibaba/ilogtail/pull/703 ，您可以查看一下。解析地址的问题感谢您指出来，已经更正；client.Send()造成崩溃的原因已经定位到了，SendHeartbeat函数中将AgentAttributes添加到HeartBeatRequest的方式使用的是set_allocated_attributes方法，而这在proto3中不能被很好的支持，造成了内存问题，修改为MergeFrom方法后，经过测试已经可以正常发送心跳

@Takuka0311 刚试了一下确实解决了，请问是通过日志中backtrace生成的栈信息中的内存地址结合汇编代码解决的吗？如果方便的希望能告知下大概过程，很是好奇…

**Comment by messixukejia** [comment]
@CyshallChan 方便的话钉钉或者微信联系下我（徐可甲）吧，我们可以交流下。

**Comment by Takuka0311** [comment]
> > 我提交了一版解决方案 #703 ，您可以查看一下。解析地址的问题感谢您指出来，已经更正；client.Send()造成崩溃的原因已经定位到了，SendHeartbeat函数中将AgentAttributes添加到HeartBeatRequest的方式使用的是set_allocated_attributes方法，而这在proto3中不能被很好的支持，造成了内存问题，修改为MergeFrom方法后，经过测试已经可以正常发送心跳
> 
> @Takuka0311 刚试了一下确实解决了，请问是通过日志中backtrace生成的栈信息中的内存地址结合汇编代码解决的吗？如果方便的希望能告知下大概过程，很是好奇…

我是通过分析crash stack，定位到问题出在HeartBeatRequest类的对象heartBeatReq上，在析构时报错，然后发现添加attributes的部分可能存在问题，查阅资料并测试后解决的

**Comment by CyshallChan** [comment]
> > > 我提交了一版解决方案 #703 ，您可以查看一下。解析地址的问题感谢您指出来，已经更正；client.Send()造成崩溃的原因已经定位到了，SendHeartbeat函数中将AgentAttributes添加到HeartBeatRequest的方式使用的是set_allocated_attributes方法，而这在proto3中不能被很好的支持，造成了内存问题，修改为MergeFrom方法后，经过测试已经可以正常发送心跳
> > 
> > 
> > @Takuka0311 刚试了一下确实解决了，请问是通过日志中backtrace生成的栈信息中的内存地址结合汇编代码解决的吗？如果方便的希望能告知下大概过程，很是好奇…
> 
> 我是通过分析crash stack，定位到问题出在HeartBeatRequest类的对象heartBeatReq上，在析构时报错，然后发现添加attributes的部分可能存在问题，查阅资料并测试后解决的

好的，感谢，现在随时可以关闭该issue了。
