### ISSUE TITLE
[QUESTION]:  user_local_config  log_type use plugin   and inputs detail is service_docker_stdout

### ISSUE THREAD

**Issue by Doslin** [alibaba/ilogtail#70]
container caused /dev/mem: No such file or directory
![image](https://user-images.githubusercontent.com/29807388/147826637-a9a02fa8-fa34-402d-a0fa-9bd194fd72c0.png)
![image](https://user-images.githubusercontent.com/29807388/147826681-fab591f4-0694-47a4-9e68-d3b3197ecb0d.png)

**Comment by EvanLjp** [comment]
Please provide the ilogtail images which you are using?

**Comment by EvanLjp** [comment]
If you stll have problem, please reopen this issue.
