### ISSUE TITLE
[FEATURE]:  failed to add inotify watcher for dir, allowd inotify watchers:3000

### ISSUE THREAD

**Issue by nysyzp** [alibaba/ilogtail#701]
failed to add inotify watcher for dir, allowd inotify watchers:3000

could you add this param at config?

**Comment by yyuuttaaoo** [comment]
The param is available as `default_max_inotify_watch_num`.
Adjusting this parameter may lead to an increase in CPU and memory usage.
You may also need to adjust kernel param: https://unix.stackexchange.com/a/13757
