### ISSUE TITLE
How to debug in Windows

### ISSUE THREAD

**Issue by yaobo-lab** [alibaba/ilogtail#82]
I'm in a Windows computer,how can i debug . thx!

**Comment by EvanLjp** [comment]
your can debug the Main method, main/plugin_main.go:33, do u meet some problems?

**Comment by yaobo-lab** [comment]
> your can debug the Main method, main/plugin_main.go:33, do u meet some problems?

ilogtail , when Initialization , dynamic loading: libPluginAdaptor

and then , cgo windows  Throw an error:

`Build Error: go build -o C:\Users\ADMINI~1\AppData\Local\Temp\__debug_bin2619742981.exe -gcflags all=-N -l .
# github.com/alibaba/ilogtail/pkg/logtail
E:/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible ..\pkg\logtail/PluginAdapter.dll when searching for -lPluginAdapter
E:/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible ..\pkg\logtail/PluginAdapter.dll when searching for -lPluginAdapter
E:/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lPluginAdapter
collect2.exe: error: ld returned 1 exit status (exit status 2)`

how can i sovle it ?  thx a lot

**Comment by EvanLjp** [comment]
in the root package : cp  pkg/logtail/PluginAdapter.dll main

**Comment by EvanLjp** [comment]
If you still have the problem , please contact with us by DingTalk.

**Comment by hessonsu** [comment]
PluginAdapter.dll是32的吗？
如何找到64位的@ 

> If you still have the problem , please contact with us by DingTalk.

**Comment by hessonsu** [comment]
修改环境变量
 GOARCH=386
不会报链接失败，但是报另外一个错！
