### ISSUE TITLE
[BUG]: heart beat test  throw runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wlazjr** [alibaba/ilogtail#860]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version:
  master

**Comment by wlazjr** [comment]
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/bannong/.gvm/pkgsets/go1.18/global #gosetup
/usr/local/opt/go/libexec/bin/go test -c -o /private/var/folders/k3/85v_b8n10t7ds_fck4jljqpm0000gq/T/GoLand/___1TestAgentSendMessage_in_github_com_alibaba_ilogtail_config_server_service_test.test github.com/alibaba/ilogtail/config_server/service/test #gosetup
/usr/local/opt/go/libexec/bin/go tool test2json -t /private/var/folders/k3/85v_b8n10t7ds_fck4jljqpm0000gq/T/GoLand/___1TestAgentSendMessage_in_github_com_alibaba_ilogtail_config_server_service_test.test -test.v -test.paniconexit0 -test.run ^\QTestAgentSendMessage\E$
=== RUN   TestAgentSendMessage

	0:Test ilogtail-1 send Heartbeat. E
Errors:

  * /Users/bannong/code/ilogtail/config_server/service/test/interface_test.go 
  Line 747: - runtime error: invalid memory address or nil pointer dereference 
  goroutine 87 [running]:
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/reporting/reports.go:150 +0x3f
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/reporting/reports.go:123 +0x5d
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:253 +0xe5
  panic({0x1685800, 0x1c5eb00})
  	/usr/local/opt/go/libexec/src/runtime/panic.go:838 +0x207
  github.com/alibaba/ilogtail/config_server/service/model.(*AgentAttributes).ParseProto(...)
  	/Users/bannong/code/ilogtail/config_server/service/model/agent.go:44
  github.com/alibaba/ilogtail/config_server/service/manager/agent.(*AgentManager).HeartBeat(0xc0001de100, 0xc000493380, 0xc00047eb40)
  	/Users/bannong/code/ilogtail/config_server/service/manager/agent/agent_operator.go:32 +0x82
  github.com/alibaba/ilogtail/config_server/service/interface/agent.HeartBeat(0x40?)
  	/Users/bannong/code/ilogtail/config_server/service/interface/agent/status.go:47 +0x185
  github.com/gin-gonic/gin.(*Context).Next(...)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
  github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000602680, 0xc000104300)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 +0x671
  github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000602680, {0x18482e0?, 0xc000100a00}, 0xc000104200)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 +0x1dd
  github.com/alibaba/ilogtail/config_server/service/test.HeartBeat(0xc0004c28d0?, 0xc0004c29a8, {0x1c33b20, 0x1})
  	/Users/bannong/code/ilogtail/config_server/service/test/request.go:275 +0x272
  github.com/alibaba/ilogtail/config_server/service/test.TestAgentSendMessage.func1()
  	/Users/bannong/code/ilogtail/config_server/service/test/interface_test.go:747 +0x1b2
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/discovery.go:89 +0x1b
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:279 +0x177
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:112 +0xdb
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x46a
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x22
  github.com/jtolds/gls._m(0x16bb7e0?, 0xc0004c2d01?)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x22
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0xc0001036b0?, 0x0?)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x19
  github.com/jtolds/gls.addStackTag(...)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0001036b0?)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd8
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc00007a8f0, 0xc000103650, 0xc0001de200)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x16a
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/context.go:107 +0x2a5
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/smartystreets/goconvey@v1.7.2/convey/doc.go:76 +0x8b
  github.com/alibaba/ilogtail/config_server/service/test.TestAgentSendMessage(0xc000602340)
  	/Users/bannong/code/ilogtail/config_server/service/test/interface_test.go:739 +0x13c
  testing.tRunner(0xc000602340, 0x17848e0)
  	/usr/local/opt/go/libexec/src/testing/testing.go:1439 +0x102
  created by testing.(*T).Run
  	/usr/local/opt/go/libexec/src/testing/testing.go:1486 +0x35f
  
  goroutine 1 [chan receive]:
  testing.(*T).Run(0xc000405d40, {0x1746435?, 0xff538e9e4969?}, 0x17848e0)
  	/usr/local/opt/go/libexec/src/testing/testing.go:1487 +0x37a
  testing.runTests.func1(0xc0001035c0?)
  	/usr/local/opt/go/libexec/src/testing/testing.go:1839 +0x6e
  testing.tRunner(0xc000405d40, 0xc000563cd8)
  	/usr/local/opt/go/libexec/src/testing/testing.go:1439 +0x102
  testing.runTests(0xc00047e000?, {0x1c6a260, 0x7, 0x7}, {0x1f00108?, 0x40?, 0x0?})
  	/usr/local/opt/go/libexec/src/testing/testing.go:1837 +0x457
  testing.(*M).Run(0xc00047e000)
  	/usr/local/opt/go/libexec/src/testing/testing.go:1719 +0x5d9
  main.main()
  	_testmain.go:59 +0x1aa
  
  goroutine 22 [select]:
  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0004670a0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
  created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c
  
  goroutine 10 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000404000)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x158
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea
  
  goroutine 11 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000404000)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a
  
  goroutine 12 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000404000)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x657
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x598
  
  goroutine 13 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000404000)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d6
  
  goroutine 14 [select]:
  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000466000)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
  created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c
  
  goroutine 50 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0005831e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x158
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea
  
  goroutine 51 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0005831e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a
  
  goroutine 52 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0005831e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x657
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x598
  
  goroutine 53 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0005831e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d6
  
  goroutine 54 [select]:
  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000466380)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
  created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c
  
  goroutine 15 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000583ba0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x158
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea
  
  goroutine 66 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000583ba0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a
  
  goroutine 67 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000583ba0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x657
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x598
  
  goroutine 68 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000583ba0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d6
  
  goroutine 69 [select]:
  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0000e40e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
  created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c
  
  goroutine 70 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0000ab860)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x158
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea
  
  goroutine 71 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000ab860)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a
  
  goroutine 72 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0000ab860)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x657
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x598
  
  goroutine 73 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0000ab860)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d6
  
  goroutine 74 [select]:
  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0000e4380)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
  created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c
  
  goroutine 16 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0004044e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x158
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea
  
  goroutine 82 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004044e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a
  
  goroutine 83 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0004044e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x657
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x598
  
  goroutine 84 [select]:
  github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0004044e0)
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
  created by github.com/syndtr/goleveldb/leveldb.openDB
  	/Users/bannong/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d6
  
  goroutine 85 [chan receive]:
  github.com/alibaba/ilogtail/config_server/service/manager/agent.(*AgentManager).updateAgentMessage(0xc0001de100, 0xc0005831e0?)
  	/Users/bannong/code/ilogtail/config_server/service/manager/agent/agent_operator.go:51 +0xa5
  created by github.com/alibaba/ilogtail/config_server/service/manager/agent.(*AgentManager).Init
  	/Users/bannong/code/ilogtail/config_server/service/manager/agent/agent_manager.go:30 +0xc5
  
  goroutine 86 [chan receive]:
  github.com/alibaba/ilogtail/config_server/service/manager/config.(*ConfigManager).updateConfigList(0xc00007a8c0, 0x0?)
  	/Users/bannong/code/ilogtail/config_server/service/manager/config/agent_operator.go:32 +0xa5
  created by github.com/alibaba/ilogtail/config_server/service/manager/config.(*ConfigManager).Init
  	/Users/bannong/code/ilogtail/config_server/service/manager/config/config_manager.go:34 +0x10c
  


1 total assertion

--- FAIL: TestAgentSendMessage (0.00s)

FAIL

Process finished with the exit code 1

**Comment by wlazjr** [comment]
please aggisn the fix task to  me.

**Comment by liangry** [comment]
这个问题是否已解决？
