### ISSUE TITLE
[QUESTION]:Can you specify which version of ilogtail the usecases apply to?

### ISSUE THREAD

**Issue by Serendo** [alibaba/ilogtail#87]
I see the usecases are refering binary from release page. Is this the pure opensource version or the ilogtail-C version?

I'm confused because the configuration structure in the usecases are different from the ones in the setup section.

There is no input section in the configuration file in the kafka example and there is a config_server_address. So the configuration
is not for the opensource version right?

I want to test a plaintext log file. Which input plugin should I use?

**Comment by EvanLjp** [comment]
I'm sorry for the confusion. Because the C part would be opened source in the next 6 months， so the usecases use the whole binary lib with C part to show. The Set up dir is only for GO local test cases.

**Comment by Serendo** [comment]
Thanks Evan. Is it possible to use the  ilogtail go version to read a plaintext log file?
