### ISSUE TITLE
[FEATURE]: 输出至elastic时,index索引增加日期.例如 *-log-20230529. fluent-bit是支持的.

### ISSUE THREAD

**Issue by joey-ccb** [alibaba/ilogtail#882]
**Concisely describe the proposed feature**
A clear and concise description of what you want. For example,
> The log format collected to Kafka is not friendly to subsequent processing

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement. For example,
> I would like to add an log flush method for flusher_kafka.

**Additional comments**
For example, the ideal input and output logs.
> The logs are supposed to have the following contents, e.g.,
>
> ``` json
> {"_target_":"127.0.0.1","_field_":"DISMAN-EXPRESSION-MIB::sysUpTimeInstance","_oid_":".1.3.6.1.2.1.1.3.0","_type_":"TimeTicks","_content_":"10423593"}
> ```

**Comment by shalousun** [comment]
@joey-ccb Welcome to contribute by submitting a pull request (PR)

**Comment by liangry** [comment]
https://github.com/alibaba/ilogtail/pull/979
