### ISSUE TITLE
[DOC]: 输出elastic的说明文档配置问题

### ISSUE THREAD

**Issue by joey-ccb** [alibaba/ilogtail#883]
Please describe any errors, ambiguities, or other improvement opportunities that you can find in the documentation.

flushers:
  - Type: flusher_elasticsearch
    Addresses:
      - http://10.8.0.118:30201

需要增加 <http://> 连接才生效

**Comment by liangry** [comment]
https://github.com/alibaba/ilogtail/pull/979
