### ISSUE TITLE
ilogtail采集kubernetes容器里日志文件

### ISSUE THREAD

**Issue by opshongwu** [alibaba/ilogtail#928]
能否在用户手册里写一个ilogtail采集kubernetes容器里日志文件的示例，方便新用户快速上手。
场景：ilogtail 以daemonset方式运行，采集到的日志发往ES或者kafka
用户只需要配置容器里日志文件具体路径就行，

**Comment by messixukejia** [comment]
https://github.com/alibaba/ilogtail/tree/main/example_config

这里面有一些样例。欢迎补充下更多场景。

**Comment by opshongwu** [comment]
场景: kubernetes容器内日志文件采集，ilogtail -> Kafka -> Elasticsearch

我在测试NGINX标准输出时，可以采集到日志，但是采集容器内NGINX日志文件时，无法采集到。不知道是哪里配置有问题，所以想看看有没有示例参考下。

**Comment by opshongwu** [comment]
已经到采集样例，谢谢。
参考 https://zhuanlan.zhihu.com/p/544079650

**Comment by messixukejia** [comment]
原因麻烦发一下吧
