### ISSUE TITLE
[BUG]:docker部署时 net=host ，app_info.json读取宿主机 本机ip的 bug

### ISSUE THREAD

**Issue by TuShengTao** [alibaba/ilogtail#957]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.
docker部署时 net=host ，app_info.json读取宿主机 本机ip的 bug，具体情况描述如图片：
    
![image](https://github.com/alibaba/ilogtail/assets/50161350/5b423fa5-8dca-4d40-9895-229398ed3aaf)

**iLogtail Running Environment**
Please provide the following information:

- ilogtail version:
  1.5.1
- Yaml configuration:

- ilogtail.LOG:

- logtail_plugin.LOG:

**Comment by yyuuttaaoo** [comment]
请问一下，在容器内执行hostname -i得到的IP是哪个？

**Comment by TuShengTao** [comment]
docker run  -d --net=host --name docker-log registry.cn-hangzhou.aliyuncs.com/log-service/logtail
上面是我运行容器的命令。
![image](https://github.com/alibaba/ilogtail/assets/50161350/bbc38ccd-d65c-4df7-8372-74acfbda357f)

上面是容器内的情况，app_info.json获取的ip不对，应该获取172.24.17.103 而不是 172.23.57.58 
![image](https://github.com/alibaba/ilogtail/assets/50161350/0f3b6e59-d727-40b4-974f-a2baa8550ba1)
上面是我宿主机的ip
![image](https://github.com/alibaba/ilogtail/assets/50161350/d5dd1dc7-dd57-46c6-900e-62915f72c554)
上面是宿主机里面执行的相关命令

**Comment by TuShengTao** [comment]
我觉得 云服务器这种情况应该蛮多的吧，简单的方法就是 部署文档里完善一下

**Comment by messixukejia** [comment]
这个事情下次双周会能否一起来交流下？

**Comment by TuShengTao** [comment]
请问是什么时间，怎样的流程? 以及我需要准备什么？

**Comment by messixukejia** [comment]
![image](https://github.com/alibaba/ilogtail/assets/13250519/0d0c9864-4069-4ad6-a750-92ce5b57e314)
关注下这里的公告吧，我们也会群里发。

可以把自己的想法在这个discussion中描述下，到时候会上发表意见就可以了。

**Comment by yyuuttaaoo** [comment]
可以考虑将hostAddr里的address都取下来，并使用if的地址做校验，校验通过的优先作为本机地址。

**Comment by TuShengTao** [comment]
> 可以考虑将h_addr_list里的address都取下来，并使用ifr_addr的地址做校验，校验通过的优先作为本机地址，如果都通不过还是取第一个。这样既不破坏既有顺序，也不会轻易取到错误地址。

是的，这个思路可以的，预计近两天会提交上去。

**Comment by messixukejia** [comment]
> [TuShengTao](/TuShengTao)

👍🏻，方便的话可以在这里登记下使用场景，多谢。https://github.com/alibaba/ilogtail/issues/693

ilogtail发展离不开大家的共同努力。
