### ISSUE TITLE
[ENHANCEMENT]: Use env to control ilogtail log level

### ISSUE THREAD

**Issue by yyuuttaaoo** [alibaba/ilogtail#959]
**Concisely describe the proposed feature**
当前在K8s环境中打印debug日志需要进入容器修改配置，这个操作有些繁琐
<https://github.com/alibaba/ilogtail/discussions/288>

**Describe the solution you'd like (if any)**
增加一个env开关，如ALIYUN_LOGTAIL_LOG_LEVEL对日志level进行覆盖，更方便调整日志级别

**Comment by zhu733756** [comment]
Hi @yyuuttaaoo , 大佬，我整了一个pr，有时间帮忙看看嘛
