### ISSUE TITLE
[QUESTION]:ilogtail以后的开发语言是以GO为主还是以C++为主？C++版何时会开源呢

### ISSUE THREAD

**Issue by xiaoping1988** [alibaba/ilogtail#96]
ilogtail以后的开发语言是以GO为主还是以C++为主？C++版何时会开源呢

**Comment by messixukejia** [comment]
iLogtail完整的功能由两部分组成：

**Comment by messixukejia** [comment]
> 

iLogtail完整的功能由两部分组成：
1、插件部分，Golang实现，目前已开源。主要是采集数据源、处理方式、容器场景支持等的扩展。
2、iLogtail基础进程，C++开发，主要是一些配置管控、文件采集的功能，预计6月份开源，到时会给出方案。

综上，iLogtail开发语言会涉及Golang跟C++，一般情况下偏向业务处理还是插件涉及会多些。

**Comment by messixukejia** [comment]
你好，ilogtail已整体开源。

https://github.com/alibaba/ilogtail/issues/176
[开源文档](https://ilogtail.gitbook.io/ilogtail-docs/about/readme)
[宣传文章](https://mp.weixin.qq.com/s/Cam_OjPWhcEj77kqC0Q1SA)
